site_name: E-857
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tooltips
  language: es
  palette:
  # Palette toggle for light mode -> https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
    - scheme: default
      toggle:
        icon: material/brightness-4 
        name: Cambiar a modo oscuro
      primary: brown
      accent: deep orange
  # Palette toggle for dark mode      
    - scheme: slate 
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo claro    
      primary: brown
      accent: deep orange

markdown_extensions:
  # Activated addons, check documentation
  - abbr
  - admonition
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details  
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.superfences      

extra_css:
  # Custom CSS for a lot of stuff
  - stylesheets/extra.css

extra:
  status:
  # Adds tooltip to the 'new' icon
    new: Recién actualizado
  # Footer social links  
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/z1sn
    - icon: fontawesome/brands/spotify
      link: https://open.spotify.com/user/zisn      
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/z1sn/
  # Hides: Made with Material for MkDocs footer     
  generator: false      

copyright: |
  &copy; 2023 <a href="https://github.com/z1sn" style="color:white" target="_blank" rel="noopener">z1sn</a> — Con la ayuda de <a href="https://pages.github.com/" style="color:white" target="_blank" rel="noopener">GitHub Pages</a> 